/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_tangentmc_RoboticArmJNI */

#ifndef _Included_net_tangentmc_RoboticArmJNI
#define _Included_net_tangentmc_RoboticArmJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_tangentmc_RoboticArmJNI
 * Method:    setServo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_tangentmc_RoboticArmJNI_setServo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_tangentmc_RoboticArmJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_tangentmc_RoboticArmJNI_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
